### ISSUE TITLE
Error: Timeout (control socket)

### ISSUE THREAD

**Issue by unocunderscoreu34** [SamKirkland/FTP-Deploy-Action#222] opened 2021-08-31 05:01 UTC
<img width="947" alt="image" src="https://user-images.githubusercontent.com/77198371/131444632-b9ec217d-0a46-4f9a-aeca-5f68683b1b55.png">

How to resolve this problem?

<img width="437" alt="image" src="https://user-images.githubusercontent.com/77198371/131444746-e950950d-dd2f-468c-bc18-a76f52b25130.png">

**Comment by PerchunPak** [comment] 2021-09-07 12:32
same

**Comment by PerchunPak** [comment] 2021-09-07 12:42
If you tried use sftp instead ftps, support of this was removed in 3576f3af9ca11d10544489b6dfca4d22e4b4c5cb so try to use previous version

**Comment by Stanvdh96** [comment] 2021-10-01 15:12
I am still experiencing this issue.
Anybody have a solution?

**Comment by plthon** [comment] 2021-10-06 06:40
Same, do you manage to find out the solution? What I do is just keep re-running the job until it is done before the timeout threshold which I believe is 30s only. Is there anyway to increase this limit?

**Comment by PerchunPak** [comment] 2021-10-06 07:24
I just used SFTP with this module, which doesn't support it. So I use 3.1.1 which is still support SFTP

**Comment by SamKirkland** [comment] 2021-10-09 22:48
Duplicate of #106 
Still no solution for this one, sorry guys.

**Closed by SamKirkland** 2021-10-09 22:48 UTC
