### ISSUE TITLE
Error: Timeout (control socket) in Sync files

### ISSUE THREAD

**Issue by Dnowdd** [SamKirkland/FTP-Deploy-Action#251] opened 2021-12-25 17:39 UTC
my deploy is giving an error in the Sync Files part
Error: Error: Timeout (control socket)

**My Action Config**
```
on: 
  push: 
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        server-dir: public_html/

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Discord Commits
        uses: Sniddl/discord-commits@v1.3
        with:
          webhook: ${{ secrets.discord_webhook }}
          message: "Novo commit em **{{ github.context.payload.repository.owner.name }}/{{ github.context.payload.repository.name}}**.\nLink: {{ github.context.payload.compare }}"
          embed: '{ "color": 201042, "title": "{{ commit.title }}", "description": "{{ commit.description }}", "url": "{{ commit.url }}", "author": { "name": "{{ commit.author.name }} ({{ commit.author.username }})", "icon_url": "https://riftmaker.com/resources/images/logos/logo-initials-background.png"} }'
          last-commit-only: false
```

**My Action Log**
```
Run SamKirkland/FTP-Deploy-Action@4.2.0
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
Failed to connect, are you sure your server works via FTP or FTPS? Users sometimes get this error when the server only supports SFTP.

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

Error: Timeout (control socket)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.2.0/dist/index.js:4778:58)
    at Object.onceWrapper (events.js:299:28)
    at Socket.emit (events.js:210:5)
    at Socket._onTimeout (net.js:469:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Error: Error: Timeout (control socket)
```

**Comment by arielbonardo** [comment] 2022-01-05 18:16
# Hi, after the "with:" add the lines, so that it retries the connection with the FTP Server and makes 3 retries
timeout_minutes : 1 
max_attempts : 3

######################################################################################

#My code is this:

on:
  push:
    branches: [ master ]

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        timeout_minutes : 1 
        max_attempts : 3 
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/
        exclude: |
          **/.git*
          README.md

# Good luck!

**Comment by NilsChr** [comment] 2022-01-11 14:04
Hi, when im trying to add these lines i get an error saying these arguments are not allowed. 
Could you provide a short example please? I'm having the same issue

**Comment by dkrape** [comment] 2022-01-29 10:41
Also having this problem.

A few notes on my setup:
- SamKirkland/FTP-Deploy-Action@4.2.0
- Dreamhost (VPS)
- Using ftps
- SSH is enabled by default, but I disabled it and still have this problem
- Hasn't worked once (I saw some people that this was intermittent)
- Connected via FTP software (Transmit) with the same port/credentials/etc. and it works fine

Thanks for any help you can provide! Happy to share more details.

**Comment by dendrofen** [comment] 2022-02-03 20:51
Do version v2.0.0 include functional to upload only changed files?

**Comment by SamKirkland** [comment] 2022-03-05 02:49
Duplicate of #106 
No real fix for this besides using non encrypted ftp. As a router between the host and destination is killing the connection.

**Closed by SamKirkland** 2022-03-05 02:49 UTC

**Comment by theaustinthompson** [comment] 2023-02-02 18:21
I encountered the same issue and was able to fix it by using the server IP address in place of the ftp.your-server-here.com. Hope this helps others!

**Comment by maruf3535** [comment] 2024-03-18 21:07
> I encountered the same issue and was able to fix it by using the server IP address in place of the ftp.your-server-here.com. Hope this helps others!

I can't solve yet in this way.
