### ISSUE TITLE
Error: Timeout (control socket)

### ISSUE THREAD

**Issue by vitortoigo** [SamKirkland/FTP-Deploy-Action#359] opened 2023-01-08 22:04 UTC
Hello,
I`m receiving this error:

`Error: Timeout (control socket)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.1/dist/index.js:5[28](https://github.com/ellitedigital/zanbor2022_loja/actions/runs/3869135514/jobs/6595043814#step:9:29)8:58)
    at Object.onceWrapper (events.js:420:28)
    at Socket.emit (events.js:[31](https://github.com/ellitedigital/zanbor2022_loja/actions/runs/3869135514/jobs/6595043814#step:9:32)4:20)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Error: Error: Timeout (control socket)`

I tested with another host and works normally, but in HostOne i get the error.
Possibly IP Block?
I`m using CPanel, anyone knows what to do?
Thanks!!

**Comment by vitortoigo** [comment] 2023-01-12 22:58
Ok, the problem is: firewall blocking.
Anyone knows what to do?
What ip list i can whitelist? (Tested with github https://api.github.com/meta actions ip, but dnt working)

**Comment by SamKirkland** [comment] 2024-03-02 20:50
Closing as duplicate of #106

**Closed by SamKirkland** 2024-03-02 20:50 UTC
