### ISSUE TITLE
Cant remove directory using RMD command, wrong directory

### ISSUE THREAD

**Issue by ramapradanaaaa** [SamKirkland/FTP-Deploy-Action#208] opened 2021-07-17 13:13 UTC
Error on delete empty directory. I think the problem is that you are not in the correct directory to run the RMD command
Below are the full log

> CDUP
< 250 OK. Current directory is /vendor/guzzlehttp/psr7

> RMD vendor/guzzlehttp/psr7/vendor-bin/
< 550 Can't remove directory: No such file or directory

> CWD /
< 250 OK. Current directory is /

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 550 Can't remove directory: No such file or directory
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3945:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3786:44)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 550
}
Error: FTPError: 550 Can't remove directory: No such file or directory

After you CDUP to /vendor/guzzlehttp/psr7 I think you should just run RMD vendor-bin instead. I have tested it using client FTP and its working well

**Comment by zuludevlab** [comment] 2021-07-17 13:30
fyi, t is on version 4.1.0

**Comment by SamKirkland** [comment] 2021-10-09 23:04
Duplicate of #220

**Closed** 2021-10-09 23:04 UTC
