### ISSUE TITLE
Hello, is this error something to do with server error? because I even tried to put the password directly on yml, still not able to update.

### ISSUE THREAD

**Issue by kimmohito** [SamKirkland/FTP-Deploy-Action#335] opened 2022-11-14 04:37 UTC
I got this error, i tested FTP it works. But deployment doesn't work on git push. Even tried with plain-text username and password. Still got this error.
```
❌ 📂 Sync files
```
```
Run SamKirkland/FTP-Deploy-Action@4.3.3
  with:
    server: ftp.rojakcube.com
    username: ***
    password: ***
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
Failed to connect, are you sure your server works via FTP or FTPS? Users sometimes get this error when the server only supports SFTP.

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

Error: Timeout (control socket)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.3/dist/index.js:5[2](https://github.com/kimmohito/github-ftp/actions/runs/3845314257/jobs/6549322522#step:3:2)88:58)
    at Object.onceWrapper (node:events:509:28)
    at Socket.emit (node:events:[3](https://github.com/kimmohito/github-ftp/actions/runs/3845314257/jobs/6549322522#step:3:3)90:28)
    at Socket._onTimeout (node:net:[5](https://github.com/kimmohito/github-ftp/actions/runs/3845314257/jobs/6549322522#step:3:5)01:8)
    at listOnTimeout (node:internal/timers:55[7](https://github.com/kimmohito/github-ftp/actions/runs/3845314257/jobs/6549322522#step:3:8):[17](https://github.com/kimmohito/github-ftp/actions/runs/3845314257/jobs/6549322522#step:3:18))
    at processTimers (node:internal/timers:500:7)
Error: Error: Timeout (control socket)
```

**Comment by samfrank** [comment] 2022-11-28 01:43
I am getting the exact same issue - did you managed to work out why this was happening?

**Comment by FluffaTheDuck** [comment] 2022-11-28 16:46
Same issue same error, i got it today while working on my school project, thought it was my webhosting provider that had a hickup. I'm using GoDaddy and it worked earlier last week.

**Comment by SamKirkland** [comment] 2024-03-02 20:51
Closing as duplicate of #106

**Closed by SamKirkland** 2024-03-02 20:51 UTC
