### ISSUE TITLE
Need Help: 

### ISSUE THREAD

**Issue by BWS-Andreas** [SamKirkland/FTP-Deploy-Action#217] opened 2021-08-16 16:02 UTC
Need help. Sorry for choosing this route! Haven't found any expert.

Our GitHub Deploy workflow with the build step "SamKirkland/FTP-Deploy-Action@3.1.1" ran for 3 months without errors. We haven't made any changes to our project on GitHub. But today we have this message in the log file:
"The repository 'http://security.debian.org/debian-security stable / updates Release' does not have a Release file."

Is that a problem with GitHub, Debian, or FTP Deploy? How can I fix the problem?!
Maybe switching to version 4.1.0 will help, but will the connection with our server (SFTP / SSH) work ?!

[deployment_dev.yml.txt](https://github.com/SamKirkland/FTP-Deploy-Action/files/6993694/deployment_dev.yml.txt)
[2_Build SamKirklandFTP-Deploy-Action@3.1.1.txt](https://github.com/SamKirkland/FTP-Deploy-Action/files/6993685/2_Build.SamKirklandFTP-Deploy-Action%403.1.1.txt)

**Comment by Olzie-12** [comment] 2021-08-16 16:41
> Need help. Sorry for choosing this route! Haven't found any expert.
> 
> Our GitHub Deploy workflow with the build step "SamKirkland/FTP-Deploy-Action@3.1.1" ran for 3 months without errors. We haven't made any changes to our project on GitHub. But today we have this message in the log file:
> "The repository 'http://security.debian.org/debian-security stable / updates Release' does not have a Release file."
> 
> Is that a problem with GitHub, Debian, or FTP Deploy? How can I fix the problem?!
> Maybe switching to version 4.1.0 will help, but will the connection with our server (SFTP / SSH) work ?!
> 
> [deployment_dev.yml.txt](https://github.com/SamKirkland/FTP-Deploy-Action/files/6993694/deployment_dev.yml.txt)
> [2_Build SamKirklandFTP-Deploy-Action@3.1.1.txt](https://github.com/SamKirkland/FTP-Deploy-Action/files/6993685/2_Build.SamKirklandFTP-Deploy-Action%403.1.1.txt)

I'm also having this exact issue. I need to use 3.1.1 only because of SFTP and all of my actions are failing (https://img.olziedev.com/429429v429429aSa_VMT.png) because it cannot get it from debian.

**Comment by SamKirkland** [comment] 2021-08-16 17:05
Duplicate of issue #216

**Closed by SamKirkland** 2021-08-16 17:05 UTC
