### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by PatoFranco** [SamKirkland/FTP-Deploy-Action#276] opened 2022-02-28 14:08 UTC
Hey! Thanks for your awesome solution. I just have a question regarding an issue im having: do you know what could be happening? I changed the username, server and password only.

Thanks!

Patricio.

Run SamKirkland/FTP-Deploy-Action@4.3.0
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
Failed to connect, are you sure your server works via FTP or FTPS? Users sometimes get this error when the server only supports SFTP.

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

Error: Timeout (control socket)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.0/dist/index.js:4808:58)
    at Object.onceWrapper (events.js:299:28)
    at Socket.emit (events.js:210:5)
    at Socket._onTimeout (net.js:4[6](https://github.com/gbmofficial/gbmland/runs/5360603877?check_suite_focus=true#step:3:6)9:8)
    at listOnTimeout (internal/timers.js:531:1[7](https://github.com/gbmofficial/gbmland/runs/5360603877?check_suite_focus=true#step:3:7))
    at processTimers (internal/timers.js:475:7)
Error: Error: Timeout (control socket)

**Comment by SaiSurya9999** [comment] 2022-03-03 17:03
I am also facing the same issue from today. I did not change anything. Till yesterday it worked without any issues. Don't know what could be the reason please help. I have used the same credentials and checked it in Core FTP client in windows, It is connecting to my cpanel server without any issues. But this actions is timing out.

Run SamKirkland/FTP-Deploy-Action@4.2.0
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
Failed to connect, are you sure your server works via FTP or FTPS? Users sometimes get this error when the server only supports SFTP.

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

Error: Timeout (control socket)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.2.0/dist/index.js:4778:58)
    at Object.onceWrapper (events.js:420:28)
    at Socket.emit (events.js:314:20)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:4[9](https://github.com/SaiSurya9999/Aspireinsci/runs/5410644118?check_suite_focus=true#step:7:9)7:7)
Error: Error: Timeout (control socket)

**Comment by danieluac** [comment] 2022-03-03 17:25
I am getting the same issue, what happening? 😢

Em qui, 3 de mar de 2022 18:03, Sai Surya ***@***.***>
escreveu:

**Comment by SaiSurya9999** [comment] 2022-03-04 02:31
> I am also facing the same issue from today. I did not change anything. Till yesterday it worked without any issues. Don't know what could be the reason please help. I have used the same credentials and checked it in Core FTP client in windows, It is connecting to my cpanel server without any issues. But this actions is timing out.
> 
> ## Run SamKirkland/FTP-Deploy-Action@4.2.0
> ## 🚀 Thanks for using ftp-deploy. Let's deploy some stuff!
> If you found this project helpful, please support it by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge Failed to connect, are you sure your server works via FTP or FTPS? Users sometimes get this error when the server only supports SFTP.
> 
> ## -------------- 🔥🔥🔥 an error occurred 🔥🔥🔥 --------------
> ## ---------------------- full error below ----------------------
> Error: Timeout (control socket) at Socket. (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.2.0/dist/index.js:4778:58) at Object.onceWrapper (events.js:420:28) at Socket.emit (events.js:314:20) at Socket._onTimeout (net.js:483:8) at listOnTimeout (internal/timers.js:554:17) at processTimers (internal/timers.js:4[9](https://github.com/SaiSurya9999/Aspireinsci/runs/5410644118?check_suite_focus=true#step:7:9)7:7) Error: Error: Timeout (control socket)

After 9 hours it is working again as expected all workflows are running fine. It is probably due to IP address block at the Server provider. I have used [haythem/public-ip](https://github.com/haythem/public-ip) to know the IP address of the shared hosted runner and checked it with the service provider in my case namecheap.com .

**Comment by SamKirkland** [comment] 2022-03-05 02:48
Duplicate of #106 
No real fix for this besides using non encrypted ftp. As a router between the host and destination is killing the connection.

**Closed by SamKirkland** 2022-03-05 02:48 UTC
