### ISSUE TITLE
Exclude Function not working

### ISSUE THREAD

**Issue by coloralp** [SamKirkland/FTP-Deploy-Action#203] opened 2021-07-01 09:32 UTC
Hi the exclusion given as an example is not working. It gives syntax error on github.

**Comment by baba43** [comment] 2021-07-01 15:41
Same here.

**Comment by superhize** [comment] 2021-07-03 20:39
Hey, you can use
`exclude: '.git*, .git*/**, README.MD]'`
https://github.com/SamKirkland/FTP-Deploy-Action/issues/202#issuecomment-869806105
#200

**Comment by DemianX0** [comment] 2021-07-08 00:53
Duplicate of #202

**Comment by christrunk** [comment] 2021-07-23 13:37
Agreed here, the documentation is wrong, it's missing the single quote wrapper

**Comment by SamKirkland** [comment] 2021-10-11 02:40
Duplicate of #202

**Closed by SamKirkland** 2021-10-11 02:40 UTC
