### ISSUE TITLE
Sync Files Error: FTPError: 550 Can't change directory to Folder/: No such file or directory

### ISSUE THREAD

**Issue by acieffe** [SamKirkland/FTP-Deploy-Action#214] opened 2021-08-05 02:32 UTC
**My Issue**
I recently tried to change my folder naming convention from camel to standard lowercase. This caused many issues but now I'm down to only one. Any push I do, it tries to add all the new files (with the folders with lowercase). this is done with no issue. But it then tried to delete the old files and folders with the camel case and either can't find them or says I don't have permission. I even tried to add back the old files with the camel case for it to delete them, but it still comes up with the error.

**My Action Config**
```on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.ftp_ftpname }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /public_html/
```

**My Action Log**
```
Run SamKirkland/FTP-Deploy-Action@4.1.0
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
----------------------------------------------------------------
Last published on 📅 Sunday, August 1, 2021, 4:26 PM
----------------------------------------------------------------
Local Files:	116
Server Files:	116
----------------------------------------------------------------
Calculating differences between client & server
----------------------------------------------------------------
⚖️  File content is the same, doing nothing: css/style.css
📁 Create: fineart
📁  Delete: FineArt    
📁 Create: fineart/css
📁  Delete: FineArt/css    
➕ Upload: fineart/css/styles.css
🗑️  Delete: FineArt/css/styles.css    
... ... ...
----------------------------------------------------------------
Making changes to 160 files/folders to sync server state
Uploading: 10.6 MB -- Deleting: 4.16 MB -- Replacing: 1.58 kB
----------------------------------------------------------------
creating folder "fineart/"
creating folder "fineart/css/"
creating folder "fineart/scripts/"
creating folder "finecode/"
creating folder "finecode/css/"
... ... ...
replacing "index.html"
removing "FineArt/css/styles.css"
File not found or you don't have access to the file - skipping...
removing "FineArt/index.html"
File not found or you don't have access to the file - skipping...
removing "FineArt/README.md"
File not found or you don't have access to the file - skipping...
... ... ...
File not found or you don't have access to the file - skipping...
removing folder "FineArt/"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 550 Can't change directory to FineArt/: No such file or directory
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3945:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3786:44)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 550
}
Error: FTPError: 550 Can't change directory to FineArt/: No such file or directory
```

**Comment by mervy** [comment] 2021-08-09 22:02
I've also had this error several times. The solution I had was to remove and recreate the repository until I had another alternative.

**Comment by Penguibird** [comment] 2021-08-31 12:10
I have fixed a similar issue that was happening to me in this fork, if you want to test this out. I'd be happy to help you if you have any issues with mine too.
https://github.com/Penguibird/FTP-Deploy-Action

**Comment by SamKirkland** [comment] 2021-10-09 23:03
Duplicate of #220

**Closed by SamKirkland** 2021-10-09 23:03 UTC

**Comment by ankur0101** [comment] 2022-07-09 10:10
> We had the same problem as it fails when deleting a "Folder" which was removed from the triggered branch pushed. The temporary fix was to remove the folders path that were removed at the latest target branch from the `.ftp-deploy-sync-state.json` file located at the target FTP server.

Removing this json file did work for me. This issue happens when the directory which was uploaded from your previous deployment has been renamed or removed in current PR/commit. To re-sync, this json file can get deleted.

**Comment by niamulhasan** [comment] 2022-07-16 18:02
> > We had the same problem as it fails when deleting a "Folder" which was removed from the triggered branch pushed. The temporary fix was to remove the folders path that were removed at the latest target branch from the `.ftp-deploy-sync-state.json` file located at the target FTP server.
> 
> Removing this json file did work for me. This issue happens when the directory which was uploaded from your previous deployment has been renamed or removed in current PR/commit. To re-sync, this json file can get deleted.

This removal worked for me

**Comment by aalzubidy** [comment] 2022-12-03 22:31
I'm having the same issue on 4.3.3, deleted the JSON file and synced everything again.
