### ISSUE TITLE
Error: FTPError: 550 Remove directory operation failed.

### ISSUE THREAD

**Issue by iwyang** [SamKirkland/FTP-Deploy-Action#220] opened 2021-08-18 05:11 UTC
FTPError: 550 Remove directory operation failed.
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3945:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3786:44)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 550
}
Error: FTPError: 550 Remove directory operation failed.

**Comment by Penguibird** [comment] 2021-08-31 12:09
I have fixed this issue in this fork, if you want to test this out.
https://github.com/Penguibird/FTP-Deploy-Action

**Comment by Sang-MHL** [comment] 2021-09-09 23:40
i guess action is using yours @Penguibird, but still same error msg...

Run Penguibird/FTP-Deploy-Action@4.2.1
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------


removing folder "just_engine/lib/temp/"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 550 Directory not found
    at FTPContext._onControlSocketData (/home/runner/work/_actions/Penguibird/FTP-Deploy-Action/4.2.1/dist/index.js:3945:39)
    at Socket.<anonymous> (/home/runner/work/_actions/Penguibird/FTP-Deploy-Action/4.2.1/dist/index.js:3786:44)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 550
}
Error: FTPError: 550 Directory not found

**Comment by florindobre90** [comment] 2021-09-22 08:40
i have the same issue ?
any updates ?

**Comment by Udik** [comment] 2021-09-23 20:40
I also have the same issue (failed to remove empty folders after removing all their contents). Also, it seems that in the case it aborts without writing the new (partial) sync state to the server, which seems to be dangerous.

**Comment by Trainax** [comment] 2021-10-18 14:31
> hello @Trainax, sorry if it's a dumb question, but i don't get it: How do you manage to do a 'new complete sync'? I was re-running the action but i'm getting the same response. And also, what is this 'sync state json' you told in your answer?

Inside the directory on the server where this action syncs the files to you can find a file called `.ftp-deploy-sync-state.json` (unless you have changed the name or location of this file using the `state-name` option) the action uses to keep track of what files have been synced and when.

If you connect to the server using an FTP client and delete this file, when you run again this action all the files in the repo will be synced again to the server even if they have not been modified

**Comment by lpldev** [comment] 2021-10-19 11:47
Understood, thanks @Trainax and @azzzub

**Comment by gavrichards** [comment] 2021-10-20 10:14
It looks like there has been [a commit which fixes this](https://github.com/SamKirkland/FTP-Deploy-Action/commit/ba86a1bf132dbb3cb5d7e9b6b556ac26f9046fd6) and marked as 4.2.0 beta, but no release as of yet. Does anyone know if it's possible to use this?

**Comment by Penguibird** [comment] 2021-10-20 10:54
Does this actually fix the issue?

**Comment by JamesDelfini** [comment] 2021-11-05 12:41
> Since it doesn't fix yet, use version 4.0.0 instead of 4.1.0. `SamKirkland/FTP-Deploy-Action@4.0.0`. I think the issue is on the `ftp-deploy` dependency, since its version upgraded to 1.1.0, still looking forward 👁️

Thanks for this, downgrading to lower versions.

**Comment by timocouckuyt** [comment] 2021-11-23 10:14
Still not OK in 4.2.0. See shot below. Created a testfile.txt in a testfolder and removed the folder afterwards:

![image](https://user-images.githubusercontent.com/2678276/143006184-e9662262-9493-487d-8c28-d4c5c845975a.png)

@SamKirkland Are you able to replicate this?

// T

**Comment by timocouckuyt** [comment] 2021-11-23 14:38
> Since it doesn't fix yet, use version 4.0.0 instead of 4.1.0. `SamKirkland/FTP-Deploy-Action@4.0.0`. I think the issue is on the `ftp-deploy` dependency, since its version upgraded to 1.1.0, still looking forward 👁️

In version 4.0.0 files get removed, folder remains but doesn't throw a 550 error. So it's still an issue.

**Comment by timocouckuyt** [comment] 2021-11-23 14:39
> > Since it doesn't fix yet, use version 4.0.0 instead of 4.1.0. `SamKirkland/FTP-Deploy-Action@4.0.0`. I think the issue is on the `ftp-deploy` dependency, since its version upgraded to 1.1.0, still looking forward 👁️
> 
> Thanks for this, downgrading to lower versions works.

Which version?

**Comment by ApplecakeYT** [comment] 2021-12-07 16:02
> > > Since it doesn't fix yet, use version 4.0.0 instead of 4.1.0. `SamKirkland/FTP-Deploy-Action@4.0.0`. I think the issue is on the `ftp-deploy` dependency, since its version upgraded to 1.1.0, still looking forward 👁️
> > 
> > 
> > Thanks for this, downgrading to lower versions works.
> 
> Which version?

Version 4.0.0

**Comment by timocouckuyt** [comment] 2021-12-07 16:07
@ApplecakeYT Version 4.0.0 failes silently, see my reply above: https://github.com/SamKirkland/FTP-Deploy-Action/issues/220#issuecomment-976638554

**Comment by gavrichards** [comment] 2021-12-09 11:55
I really wish this was fixed, it's such a pain in the ass when you do a big deployment, and then near the end it fails because some directories were deleted, so you then have to redeploy the entire repo to get the "sync state" file up to date.

**Comment by ApplecakeYT** [comment] 2021-12-09 15:43
> @ApplecakeYT Version 4.0.0 fails silently, see my reply above: [#220 (comment)](https://github.com/SamKirkland/FTP-Deploy-Action/issues/220#issuecomment-976638554)

I am aware, although thanks for pointing it out. I should have mentioned that it only hides the error rather than actually fixing it.

**Comment by Penguibird** [comment] 2021-12-09 17:46
I just stopped caring about fails. I'm gonna see about fixing it at some
point but it's kind of a pain to test this.

**Comment by DanielGilB** [comment] 2021-12-12 22:21
> @ApplecakeYT Version 4.0.0 fails silently, see my reply above: [#220 (comment)](https://github.com/SamKirkland/FTP-Deploy-Action/issues/220#issuecomment-976638554)

ftp-deploy-sync-state.json is being update? If its, at least you can remove the folder + index by hand and its not necessary to resync all project.

But yes, this is a problem.

**Comment by Trainax** [comment] 2021-12-12 22:34
> ftp-deploy-sync-state.json is being updated?

In my case the action fails when it tries to delete the directory in the FTP server dir: the sync never competes, the `ftp-deploy-sync-state.json` file doesn't get updated and the directory remains on the server.

The only way I've found to make everything work again is to connect to the FTP server using an FTP client, manually delete the folder and the `ftp-deploy-sync-state.json` file and run the action again

**Comment by DanielGilB** [comment] 2021-12-13 19:19
> > ftp-deploy-sync-state.json is being updated?
> 
> In my case the action fails when it tries to delete the directory in the FTP server dir: the sync never competes, the `ftp-deploy-sync-state.json` file doesn't get updated and the directory remains on the server.
> 
> The only way I've found to make everything work again is to connect to the FTP server using an FTP client, manually delete the folder and the `ftp-deploy-sync-state.json` file and run the action again

with 4.0 ?

**Comment by Trainax** [comment] 2021-12-13 19:23
> > > ftp-deploy-sync-state.json is being updated?
> > 
> > In my case the action fails when it tries to delete the directory in the FTP server dir: the sync never competes, the `ftp-deploy-sync-state.json` file doesn't get updated and the directory remains on the server.
> > 
> > The only way I've found to make everything work again is to connect to the FTP server using an FTP client, manually delete the folder and the `ftp-deploy-sync-state.json` file and run the action again
> 
> with 4.0 ?
> 

No. I tried with 4.1.0 and 4.2.0. I might have misunderstood your previous comment, I didn't see your quote regarding version 4.0.0

**Comment by britram** [comment] 2021-12-19 10:15
Running into this problem as well (github.com/britram/trammell.ch). Can verify downgrading to 4.0.0 allows "success with silent failure" (which for this application I don't much care about). thanks all for the tips and looking forward to a fix.

**Comment by afbora** [comment] 2022-01-07 13:24
+1 please fix this issue

**Comment by gitinthehole** [comment] 2022-01-09 12:26
+1 fix requested please

**Comment by gitinthehole** [comment] 2022-01-09 14:01
In case it's helpful, modifying `ftp-deploy-sync-state.json` by removing the folders and related files that couldn't be deleted did the trick. It did trigger a rebuild but the deploy succeeded.

**Comment by afbora** [comment] 2022-01-09 14:05
Yes, I'm using this solution for now too, but it's a big waste of time in projects with a lot of files.

**Comment by gavrichards** [comment] 2022-01-09 14:48
Would anyone feel confident enough to fork it and fix the issue, if we don't feel like this is going to get resolved? Or maybe a PR if we could get the owner's attention?

**Comment by Kryptos-FR** [comment] 2022-01-15 16:57
I had a similar error today. One issue is that removal should happen in reverse order.

In my case it tried to do this:
> 📁  Delete: jekyll    
> 📁  Delete: jekyll/update    
> 📁  Delete: jekyll/update/2022    
> 📁  Delete: jekyll/update/2022/01    
> 📁  Delete: jekyll/update/2022/01/14  

And because `jekyll` was deleted first (including all its sub folder and files) it failed for the next step:

> removing folder "jekyll/"
> removing folder "jekyll/update/"
> 
> ----------------------------------------------------------------
> --------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
> ----------------------------------------------------------------
> 
> ----------------------------------------------------------------
> ----------------------  full error below  ----------------------
> ----------------------------------------------------------------
> 
> FTPError: 550 Can't change directory to update/: No such file or directory

What the action should do is remove in deep-first order:
> 📁  Delete: jekyll/update/2022/01/14  
> 📁  Delete: jekyll/update/2022/01    
> 📁  Delete: jekyll/update/2022    
> 📁  Delete: jekyll/update    
> 📁  Delete: jekyll

**Comment by Tsioriantenaina** [comment] 2022-01-22 15:49
Hello,
Don't know if this can help someone but on my end, I have resolve this to add this line: _**dangerous-clean-slate: true**_
This line remove all file in server directory before upload the new file.
 
![image](https://user-images.githubusercontent.com/41894196/150645517-c73c1104-52b6-463d-8fbd-05c4c70abb7c.png)

Hope that this can help :)

**Comment by raparthur** [comment] 2022-01-25 17:41
> Since it doesn't fix yet, use version 4.0.0 instead of 4.1.0. `SamKirkland/FTP-Deploy-Action@4.0.0`. I think the issue is on the `ftp-deploy` dependency, since its version upgraded to 1.1.0, still looking forward 👁️

FINALLY WORKED OMG!!!

**Comment by raparthur** [comment] 2022-01-25 19:07
After long searching, now in Jan/2022 I arrived at conclusion that unfortunatelly this issue still has no solution as should be, but I will follow a short routine which does the trick:
1. Execute push normally. This will throw the expected FTP 550 error, but will update your repository.
2. Delete manually ftp-deploy-sync-state.json file on FTP server root
3. Delete manually the undesired directory located on FTP server
4. Re-run push.

**Comment by raparthur** [comment] 2022-01-25 19:11
After long searching, now in Jan/2022 I arrived at conclusion that unfortunatelly this issue still has no solution as should be, but I will follow a short routine which does the trick:

    Execute push normally. This will throw the expected FTP 550 error, but will update your repository.
    Delete manually ftp-deploy-sync-state.json file on FTP server root
    Delete manually the undesired directory located on FTP server
    Change something and run push again.

**Comment by vanderHobus** [comment] 2022-01-30 00:34
+1 same problem here. 
Apparently no solution and repository has been abandoned already :(

**Comment by vanderHobus** [comment] 2022-01-30 02:39
Apparently it's an FTP user permission error.
My FTP is on an IIS server, I added permission to the user who makes the connection through IIS, and the problem stopped happening.

To test, use FileZilla (for example), login with the same login/password and try to create a folder through filezilla. Check for a permission error.

**Comment by SamKirkland** [comment] 2022-01-31 06:50
I've pushed `v4.3.0-beta` branch with a fix for this bug.
For those of you willing to test this bug fix update the `uses:` line in your action yaml file to the following

```yaml
uses: SamKirkland/FTP-Deploy-Action@v4.3.0-beta
```

Please follow up with a comment letting me know if the issue has been resolved.

Note: Once I deploy the actual `4.3.0` branch you will need to update your yaml files again as the beta branch will be destroyed.

**Comment by timocouckuyt** [comment] 2022-01-31 08:57
@SamKirkland Fix works here. I performed the following:

- Created a folder with one file in it. Pushed it. Get deployed fine.
- Removed the exact same folder including the file. Got removed fine on the server without the 550 error.

👍🏻

**Comment by afbora** [comment] 2022-02-02 13:26
@SamKirkland Yes, I can confirm too, removing directory works for @v4.3.0-beta 👏

**Closed** 2022-02-19 21:06 UTC

**Comment by gitinthehole** [comment] 2022-02-23 05:37
@SamKirkland Didn't have a chance to test this until now. Wanted to say thanks much. The latest update v4.3.0 works like a charm.

**Comment by joshigolu08** [comment] 2022-04-19 09:50
I slove this using     `      uses: SamKirkland/FTP-Deploy-Action@4.3.0
`
just change the version

**Comment by LOO2** [comment] 2022-05-15 13:28
O solve this excluding the folder error like: 
`exclude: |
          **/.vscode*
          **/.circleci*
          **/.git*
          **/.git*/**
          **/node_modules/**`

I hope I've helped!

**Comment by Incama2** [comment] 2022-07-22 16:55
For me the problem was that my cPanel hosting doesn't allow foreign FTP connections by default and I had to allow it manually.

**Comment by frontcamp** [comment] 2022-12-15 12:12
> I slove this using ` uses: SamKirkland/FTP-Deploy-Action@4.3.0` just change the version

Same thing - helped me to just change version and error "Can't delete file or folder" was lost. Thank you!

**Comment by davetapley** [comment] 2023-01-11 22:45
I just got this on 4.3.0 😞 

If it helps:
I deleted the contents of a dir called `Radar`, then in a later commit recreated it as `radar` with a single new file, before pushing both commits. It failed with:
```
replacing "tasks/radar/ncToImage.py"
...
FTPError: 550 The system cannot find the path specified. 

``

**Comment by adampweb** [comment] 2023-06-10 12:08
## The issue still exists :disappointed:

### Bug Description

My result is similar for the followings:
https://github.com/SamKirkland/FTP-Deploy-Action/issues/369#issuecomment-1426837160
https://github.com/SamKirkland/FTP-Deploy-Action/issues/220

[Here](https://github.com/SamKirkland/FTP-Deploy-Action/issues/220#issuecomment-1025430529) you wrote that you fixed the issue in the 4.3.0-beta version. But the latest version(4.3.4)still has the issue.


### My Action Config
```yaml
name: 🚀 Deploy Site to cPanel
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get the latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: 🔨 Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm prune
          npm run build --if-present
          git reset --hard

      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
```
### My Action Log
```
Run SamKirkland/FTP-Deploy-Action@v4.3.4
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
----------------------------------------------------------------
Last published on 📅 Friday, June 9, 2023, 4:17 PM
----------------------------------------------------------------
Local Files:  114
Server Files: 114
----------------------------------------------------------------
Calculating differences between client & server
----------------------------------------------------------------
📁 Create: _next/static/_RfaoSevEUUzn1m-yNWNm
📄 Upload: _next/static/_RfaoSevEUUzn1m-yNWNm/_buildManifest.js
📄 Upload: _next/static/_RfaoSevEUUzn1m-yNWNm/_ssgManifest.js
🔁 File replace: _next/BUILD_ID
🔁 File replace: _next/build-manifest.json
🔁 File replace: _next/cache/.tsbuildinfo
🔁 File replace: _next/cache/config.json
🔁 File replace: _next/cache/eslint/.cache_metchw
🔁 File replace: _next/cache/next-server.js.nft.json
🔁 File replace: _next/cache/webpack/client-production/0.pack
🔁 File replace: _next/cache/webpack/client-production/index.pack
🔁 File replace: _next/cache/webpack/server-production/0.pack
🔁 File replace: _next/cache/webpack/server-production/index.pack
🔁 File replace: _next/next-server.js.nft.json
🔁 File replace: _next/prerender-manifest.js
🔁 File replace: _next/prerender-manifest.json
🔁 File replace: _next/server/middleware-build-manifest.js
🔁 File replace: _next/server/pages/_document.js
🔁 File replace: _next/server/pages/403.html
🔁 File replace: _next/server/pages/404.html
🔁 File replace: _next/server/pages/500.html
🔁 File replace: _next/server/pages/impresszum.html
🔁 File replace: _next/server/pages/index.html
🔁 File replace: _next/trace
🔁 File replace: package-lock.json
🔁 File replace: package.json
🔁 File replace: pages/_document.tsx
📁 Delete: _next/static/febuUMLM9VbdPJgDHOCse
⚖️  File content is the same, doing nothing: _next/export-marker.json
⚖️  [...] <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<--- I dropped out irrelevant lines. There is no errors.
⚖️  File content is the same, doing nothing: tsconfig.json
----------------------------------------------------------------
Making changes to 28 files/folders to sync server state
Uploading: 830 B -- Deleting: 830 B -- Replacing: 9.18 MB
----------------------------------------------------------------
creating folder "_next/static/_RfaoSevEUUzn1m-yNWNm/"
uploading "_next/static/_RfaoSevEUUzn1m-yNWNm/_buildManifest.js"
uploading "_next/static/_RfaoSevEUUzn1m-yNWNm/_ssgManifest.js"
replacing "_next/BUILD_ID"
replacing "_next/build-manifest.json"
replacing "_next/cache/.tsbuildinfo"
replacing "_next/cache/config.json"
replacing "_next/cache/eslint/.cache_metchw"
replacing "_next/cache/next-server.js.nft.json"
replacing "_next/cache/webpack/client-production/0.pack"
replacing "_next/cache/webpack/client-production/index.pack"
replacing "_next/cache/webpack/server-production/0.pack"
replacing "_next/cache/webpack/server-production/index.pack"
replacing "_next/next-server.js.nft.json"
replacing "_next/prerender-manifest.js"
replacing "_next/prerender-manifest.json"
replacing "_next/server/middleware-build-manifest.js"
replacing "_next/server/pages/_document.js"
replacing "_next/server/pages/403.html"
replacing "_next/server/pages/404.html"
replacing "_next/server/pages/500.html"
replacing "_next/server/pages/impresszum.html"
replacing "_next/server/pages/index.html"
replacing "_next/trace"
replacing "package-lock.json"
replacing "package.json"
replacing "pages/_document.tsx"
removing folder "/_next/static/febuUMLM9VbdPJgDHOCse"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 550 Can't change directory to /_next/static/febuUMLM9VbdPJgDHOCse: No such file or directory
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:5252:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:5096:44)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 550
}
Error: FTPError: 550 Can't change directory to /_next/static/febuUMLM9VbdPJgDHOCse: No such file or directory
```

**Comment by ilias000** [comment] 2023-12-05 11:52
The issue still exists

**Comment by ms-daniel** [comment] 2024-01-09 16:52
> I had the same issue even though less than 6 months ago it was working perfectly. I tried everything and nothing worked. At the end the problem was with the permissions of the user I was using. After I gave the user all the permissions it worked perfectly.

absolute yes. thanks!

**Comment by Gordon-JeonghanKo** [comment] 2024-03-31 13:55
> I had the same issue even though less than 6 months ago it was working perfectly. I tried everything and nothing worked. At the end the problem was with the permissions of the user I was using. After I gave the user all the permissions it worked perfectly.

How can I gave a permission for the user??

**Comment by rezwansaki** [comment] 2024-04-23 19:57
Thanks for this. Please try to do it for the Laravel project. :) When I push my project, '.env' file replace automatically again and again.

**Comment by paulopereira-tec** [comment] 2024-05-08 13:16
I found a solution to the problem that might help. This apparently happens because it exceeds the open and inactive connection timeout. Same error in a C# library: https://www.chilkatsoft.com/p/p_462.asp

The solution I found was to increase the "timeout" to 2 minutes: timeout: 120000.

https://github.com/SamKirkland/FTP-Deploy-Action/issues/446#issuecomment-2100538182
